### ISSUE TITLE
Breaking on upgrade to iOS 12

### ISSUE THREAD

**Issue by kevinEsherick** [quan-to/react-native-pbkdf2#6]
First off, thanks for for your work, this lib has been working great for me until now. I just upgraded to iOS 12 on my device and updated Xcode to the iOS 12 SDK. derivationKey() wasn't working at first, so I updated the package, changing those NSNumbers to ints. With this new version, the package works, but now, given the same arguments, it's generating different keys than it was prior to the update. For example where before PBKDF2.derivationKey('foo', 'bar', 1000) would always return X, it now returns Y. This is problematic because I have data hashed from the previous version and now can't recover it. Is there any way to generate the same keys that it would have previously, given the same input? Your help is greatly appreciated.

**Comment by danielfttorres** [comment]
Hi @kevinEsherick. I can see a simple solution for this: you should use the old way (with `NSNumbers`) and the upgraded (with `Ints`). If the user trying to use the algorithm with upgraded function and the results are wrong, you can try to run with the old function and the results should be ok. The old way work as a temporary fallback to support the keys generated before. This seems to work.

**Comment by kevinEsherick** [comment]
@danielfeelfine Thanks for responding. Unfortunately the old way just isn't working no matter what. When I revert to NSNumber, derivationKey gets to int status = CCKeyDerivationPBKDF(...) in PBKDF2.m and then just doesn't work. I'm not sure what's going on. Might be that my brain is fried right now and I need to take a fresh look tomorrow. Have you tried this method and found it to work on the latest versions of XCode, iOS, and this package?

**Comment by danielfttorres** [comment]
No, I just use the upgraded method, in iOS 12. If I found the solution I will share in this issue.

**Comment by kevinEsherick** [comment]
I can confirm that this is happening on iOS 12 but not earlier versions. That is, derivationKey doesn't work once it reaches CCKeyDerivationPBKDF() when iterations is passed as an NSNumber in iOS 12 on both device and in simulator. It works in previous versions of iOS with NSNumber, or if iterations is passed as an int instead. The commit said you changed from NSNumber to int because NSNumber was slow—just how slow was it? I've waited for minutes to no avail so it doesn't appear that it's just slow, but that for some reason the function won't work with NSNumber on iOS 12. Any ideas? How is it even possible that passing iterations in as a different type of number causes the function to return a different value even though it's the same number of iterations?
**Edit:** It's possible that this is only happening in development, as I haven't received any reports or data to indicate it happening in production. Looking into that possibility now.
**EDIT 2:** It is happening in production as well. This appears to be a product of Xcode 10, as I just updated from 9 and then this started happening. Again, it only happens with devices running iOS 12. But this is a serious, breaking change for those of us who have been using this package since before the latest commit.

**Comment by kevinEsherick** [comment]
I figured out the issue after contacting Apple technicians. Changes in Apple's code were causing it. NSNumber was never a valid type to pass to CCKeyDerivation, it just happened to work. Some changes were made causing it to no longer work, which isn't a fault of Apple's since use of NSNumber was not part of their API. I'm able to reproduce the old hash that NSNumber would have produced by passing iterations in as NSNumber and then converting this to NSUInteger before passing to CCKeyDerivationPBKDF. If anyone wants to know more feel free to ask.
